### ISSUE TITLE
When choosing link type of file I get "You don't have permission to see the files on this site"  I'm an admin.

### ISSUE THREAD

**Issue by shash99** [DNNCommunity/DNN.Links#74] opened 2023-02-06 18:11 UTC
## Please summarize your question in one sentence
When choosing link type of file I get "You don't have permission to see the files on this site"  I'm an admin.

## Give a more extended description
I'm in the process of upgrading dnn to version 9.10.6.  I've installed the latest version of the links module.  This is not specific to the links module, where ever I can choose a link type of file it occurs.

## Other comments or remarks
Also, I'm unsure of why the module is saying that it's configured to use dynamic content.  What is that and how do I change that?

I also don't understand why i'm seeing folder and roles for selection.
![2023-02-01_13-47-43](https://user-images.githubusercontent.com/5889823/217051376-d399ac49-b54d-450c-9277-4f78ed5a7694.jpg)

**Comment by valadas** [comment] 2023-02-06 18:48
There is no 9.10.6, where did you get DNN from ?

**Comment by shash99** [comment] 2023-02-06 19:03
Thanks for responding.

The dnn version is:  Evoq_Basic_9.10.6.1-1_Upgrade.zip

The links version is: DNN_Links_8.0.0_Install.zip

Sharon

From: Daniel Valadas ***@***.***>
Sent: Monday, February 6, 2023 1:48 PM
To: DNNCommunity/DNN.Links ***@***.***>
Cc: Poirier, Sharon ***@***.***>; Author ***@***.***>
Subject: [EX] Re: [DNNCommunity/DNN.Links] When choosing link type of file I get "You don't have permission to see the files on this site" I'm an admin. (Issue #74)

*** CAUTION: This email originated from outside of AIPSO. ***
________________________________

There is no 9.10.6, where did you get DNN from ?

**Comment by valadas** [comment] 2023-02-06 22:34
Oh it`s Evoq... They may have something a bit different regarding permissions maybe. Can you open a ticket with them to see if they can spot anything being done wrong in this project that may be failing with Evoq since Evoq is not open-source and I cannot reproduce this issue with Platform...

**Comment by shash99** [comment] 2023-02-07 12:05
Thank for your reply, it was them who referred me to you guys.

I told them the permissions issue wasn’t specific to the links module it happened in any module that a link to the file/folder system.

As far as the links module, is there documentation for this?  I had other questions on the issue.  Why is the module configured to show  dynamic data?  I’m not even sure what that means and I can’t figure out how to turn configure it not to.

Thanks for your help,
Sharon

From: Daniel Valadas ***@***.***>
Sent: Monday, February 6, 2023 5:34 PM
To: DNNCommunity/DNN.Links ***@***.***>
Cc: Poirier, Sharon ***@***.***>; Author ***@***.***>
Subject: [EX] Re: [DNNCommunity/DNN.Links] When choosing link type of file I get "You don't have permission to see the files on this site" I'm an admin. (Issue #74)

*** CAUTION: This email originated from outside of AIPSO. ***
________________________________

Oh it`s Evoq... They may have something a bit different regarding permissions maybe. Can you open a ticket with them to see if they can spot anything being done wrong in this project that may be failing with Evoq since Evoq is not open-source and I cannot reproduce this issue with Platform...

**Comment by shash99** [comment] 2023-02-07 15:08
i have solved the permission issue with suggestion from #5088

Set the root folder to have Registered Users be able to browse and view

Still looking for information on the second half of question.

**Comment by valadas** [comment] 2023-02-07 21:01
Ok, I am closing this issue as the permissions issue is fixed, but I am not sure what you mean by second half of the question...

Can you elaborate on 
> Why is the module configured to show  dynamic data

I don't understand what you mean by this...

**Closed** 2023-02-07 21:01 UTC

**Comment by shash99** [comment] 2023-02-07 21:04
I thought I attached a screenshot. I circled it below.  I don’t know what it means or how to change it.

Is there documentation on this module?  I can’t seem to find it anywhere.

***@***.***

From: Daniel Valadas ***@***.***>
Sent: Tuesday, February 7, 2023 4:02 PM
To: DNNCommunity/DNN.Links ***@***.***>
Cc: Poirier, Sharon ***@***.***>; Author ***@***.***>
Subject: [EX] Re: [DNNCommunity/DNN.Links] When choosing link type of file I get "You don't have permission to see the files on this site" I'm an admin. (Issue #74)

*** CAUTION: This email originated from outside of AIPSO. ***
________________________________

Ok, I am closing this issue as the permissions issue is fixed, but I am not sure what you mean by second half of the question...

Can you elaborate on

Why is the module configured to show dynamic data

I don't understand what you mean by this...

**Comment by valadas** [comment] 2023-02-07 21:16
I dont think attaching to emails will make the screenshot show on github...
Can you actually go tot github and drag-drop the screenshot you want to show...

**Comment by shash99** [comment] 2023-02-07 21:24
![2023-02-01_13-47-43](https://user-images.githubusercontent.com/5889823/217368888-1b300f09-1fb1-4ec0-b86b-b490ffbef281.jpg)

**Comment by valadas** [comment] 2023-02-07 22:34
Can you open a new issue with clear steps to get into that state... If I setup the module in Folder mode I can't get to the UI to manage links...
