### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by mnioche** [DNNCommunity/DNN.Links#38] opened 2019-08-04 21:11 UTC
## Describe the bug
When editing a link, the delete option is not working. When you click on the delete link, nothing happens.

## Software Versions
- DNN: 09.03.02
- Module: 07.00.01

## To Reproduce
1. Go to Link module with a couple of links already added
2. Click on the pencil to the left of the link
3. Scroll down to delete option and click on the word delete.
4. No error but nothing happens either.

**Comment by valadas** [comment] 2021-02-02 07:21
I cannot reproduce this issue, it may be cause by some failing javascript. I am closing the issue but if you can look in the browser console (F12 in most browsers) do you see some red messages when you do click the delete button ?

**Closed by valadas** 2021-02-02 07:21 UTC
