### ISSUE TITLE
Permissions do not work when they are configured to only show a link only to unauthenticated users

### ISSUE THREAD

**Issue by jd8** [DNNCommunity/DNN.Links#1] opened 2015-09-02 15:26 UTC
I need to show a links module to all users, but one of the links in it should only show when the user is unauthenticated.  

The Links module permissions were set to show to All Users.  Under 'Links Settings', I set the Use Permissions value to Yes.  

In the Edit Links screen, the Unauthenticated Users role was selected for my link.  No other roles were selected.  However, the link shows to all users, whether they are logged in or not.

**Comment by valadas** [comment] 2018-06-29 08:18
Unauthenticated is not really a role, it is basically when we do not have a User Id.

We would need to add Unauthenticated Users and All Users in the permissions grid, currently with the latest release on Dnn 9.2, those two do not show up at all:

![image](https://user-images.githubusercontent.com/6371568/42081446-74d542f6-7b53-11e8-8093-444ac4642773.png)

**Comment by valadas** [comment] 2018-07-03 06:52
Strange, I got a comment by email from @Marnix but it is not here. I am adding it just for documentation

His comment was:
Unauthenticated, I can imagine, because you could check if someone is authenticated or not.
"All users" would simply mean everyone, which basically means "Don't use permissions" or am I missing the point

----------------
Response:
All users would be link by link, the option to not use permissions would apply to the whole module.

**Comment by trouble2** [comment] 2018-07-03 06:58
Oh yeah I read a little further and saw I kind of misunderstood, so I delete it.
Since you would set the permissions per link and set the option "Use permissions" for the complete module. So then it actually would make sense to have both options added...

**Comment by meffj00** [comment] 2019-04-03 20:38
We convert DNN Evoq to DNN platform 9.2.2 including several link modules. The conversion works good, but when you add new links they won't display when logged out. We want to show the links to everyone but where missing the check for All users! When we put a new links module on a page everything worms fine. What ckuld this be or is a bug? Thanks for your answers.

**Comment by valadas** [comment] 2021-02-02 06:52
I am closing this issue since it has been here since 2015 and nobody submitted any PR. If anyone has the intention to implement this, please do comment and I will reopen

**Closed by valadas** 2021-02-02 06:52 UTC
Labels: enhancement

**Comment by meffj00** [comment] 2021-08-28 15:55
We had the same problems with a previous version of the link module. Installing a new instance of the module on the relevant page will solve the problems i.e. all users will see the links! This issue has already been reported to GItHub before.

**Comment by TekkGuy** [comment] 2021-08-30 12:01
Meff,

Thanks for the input, unfortunately, adding a new LINKS module did not make the "All Users" role appear as a selection. It appears that even the values being used are wrong in the table ... in order for the links to be seen, the value needs to be -2 ... however, according to the ROLES table, -2 means SUPERUSER. But, if I use -1 (which means All Users) the links do not show. Very odd.

The problem is now I apparently have to tell my editors that if they make any change to a link they must immediately let me know so I can edit the records in the tables on the backend so that the links show again.

**Comment by hismightiness** [comment] 2021-08-30 19:01
Are there any notable errors that might also be logged when this use case is present?

**Comment by TekkGuy** [comment] 2021-08-31 13:01
Will,

I checked the Admin Log, nothing was recorded.
