### ISSUE TITLE
Uploading a file results in an index error

### ISSUE THREAD

**Issue by budhoward** [DNNCommunity/DNN.Links#60] opened 2021-04-30 16:39 UTC
I am trying to add a link to a file, but uploading the file from the Links module (as I'm adding), but I get an error

So I am trying to add a link via the Links module (version 7.0.1, DNN version 9.3.2 and after I select the local file to upload then click the "upload file" button I receive an error.  I don't know if this is a Links module issue, or a DB issue, or a config issue.

1. Select "edit mode" on site
2. Click "Add Link" on module
3. Select "File" for "Link Type"
4. Click "Upload New File"
5. Click "Choose File"
6. Select file from local drive, click OK, returns to edit link page
7. Click "Upload Selected File"
8. Message appears "A critical error has occurred. Please check the Event Viewer for further details."
9. Check log and find these details below
 
Message:startIndex cannot be larger than length of string. Parameter name: startIndex
StackTrace:
InnerMessage:startIndex cannot be larger than length of string. Parameter name: startIndex
InnerStackTrace:
at System.String.Substring(Int32 startIndex, Int32 length) at DotNetNuke.Common.Globals.GetSubFolderPath(String strFileNamePath, Int32 portalId) at DotNetNuke.UI.UserControls.UrlControl.cmdSave_Click(Object sender, EventArgs e) at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e) at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument) at System.Web.UI.WebControls.LinkButton.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument) at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument) at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData) at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by valadas** [comment] 2023-02-05 01:19
I cannot reproduce this issue, I am closing it but if this is still valid with the latest release of the module and DNN, please comment back and I'll re-open

**Closed by valadas** 2023-02-05 01:19 UTC
